### ISSUE TITLE
Unbolding fails on bold font-weight < 600

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-text#15]
Trying to unbold text when `b` tag has a custom font-weight of < 600 fails. The document appears to think that it's not bolded, and therefore cannot be un-bolded.

I've managed to replicate on a purely vanilla `contenteditable` element, without scribe being applied. Even so, scribe should be patching it. [Filed a bug](https://github.com/guardian/scribe/issues/442), they should be able to say whether it's something they can / will fix.

**Comment by seaneking** [comment]
This will be fixed with a new editor in #27

**Comment by seaneking** [comment]
Fixed in https://github.com/SimplaElements/simpla-text/releases/tag/v1.0.0
