### ISSUE TITLE
Changing UID to point to empty content should clear current content

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-text#22]
When changing the UID of `simpla-text` (whether via it's SID or block's UID), it will fetch content at the new UID, but if that content is empty, it retains the current value, rather than clearing it.

It looks like it's [this line here](https://github.com/SimplaElements/simpla-text/blob/master/src/simpla-text/behaviors/default.js#L45), as when there is no default value, it doesn't set `this.value`. Simple solution would be to just use an empty string if `_default` is falsey

**Comment by seaneking** [comment]
What about img and block?

**Comment by bedeoverend** [comment]
Block isn't an issue - it just changes the UIDs of its children, which on last inspection it's doing. I suspect the same is happening with `img`, I'll check it and add an issue there too if necessary.

**Comment by seaneking** [comment]
Fixed in https://github.com/SimplaElements/simpla-text/releases/tag/v1.0.0
