### ISSUE TITLE
Sanitize incoming text based on attributes

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-text#24]
Incoming text should be sanitized based on the setup of the given element. An example of this is if you've saved data into a `<simpla-text sid="blurb" block>` which will probably have `<p>` tags, and then you use `<simpla-text sid="blurb" inline>` it will load in the same data with `<p>` tags rather than being inline versions.

This also is a part of a larger problem which is sanitizing all incoming data based on what HTML tags should be allowed in `simpla-text`, whether it be in general, or specific to that `simpla-text` instance.

**Comment by seaneking** [comment]
This will be fixed with a new editor framework in #27

**Comment by seaneking** [comment]
Fixed in https://github.com/SimplaElements/simpla-text/releases/tag/v1.0.0
