### ISSUE TITLE
Specificity of cursor: text

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-text#25]
[This line](https://github.com/SimplaElements/simpla-text/blob/master/src/simpla-text/simpla-text.css#L11) can only be overridden with `simpla-text[inline]` i.e. `simpla-text` won't cut it, the use case being suppose you've embedded `simpla-text` in an `<a>` or `<button>` and never want the text cursor, you'll need an explicit understanding of how `simpla-text` is internally styled.

I would think this is a bug, though no idea if this is common / known and how / if it can be fixed.

**Comment by seaneking** [comment]
Deffo a bug

**Comment by seaneking** [comment]
Fixed in https://github.com/SimplaElements/simpla-text/releases/tag/v1.0.0
