### ISSUE TITLE
[v1] Toolbar still opens when plaintext is true

### ISSUE THREAD

**Issue by seaneking** [SimplaElements/simpla-text#41]
When `plaintext` is enabled highlighting a range of text still opens the toolbar. Clicking on tools error in the console with `Command [command] not found` - so plaintext itself is working, just need to hide the UI.

**Comment by bedeoverend** [comment]
Fixed in https://github.com/SimplaElements/simpla-text/commit/421101518c58e4b2878c901b901dfd3fce40f0f2 (why isn't GitHub automatically closing these??)

**Comment by seaneking** [comment]
Because it only closes things once commits are merged to master

**Comment by bedeoverend** [comment]
Oh...yeah...that makes sense...
