### ISSUE TITLE
[v1] Breaks with latest prosemirror-view

### ISSUE THREAD

**Issue by seaneking** [SimplaElements/simpla-text#45]
Latest version of `prosemirror-view` (which includes @bedeoverend's fix for Shadow DOM selection) breaks simpla-text, throwing errors about `.min()` of some such is not a function.

**Comment by bedeoverend** [comment]
@seaneking could you provide steps to replicate? I've updated `1.0` to use latest prosemirror deps and can't replicate, either in a demo / custom env or simpla.io

**Comment by seaneking** [comment]
I just pulled in latest `prosemirror-view` (0.20.2 I think) and everything blew up. No steps to replicate, just load simpla-text and console flooded with errors. Might have been something in my env, didn't do thorough testing. Will nuke my deps and try again once it's using prosemirror-view mainline again

**Comment by bedeoverend** [comment]
I've updated it to mainline `prosemirror-view`, pointing to a specific commit so that we get (another) patch for Shadow DOM

**Comment by seaneking** [comment]
Assuming it was an error with my env then, closing this
