### ISSUE TITLE
Value property includes style widget

### ISSUE THREAD

**Issue by seaneking** [SimplaElements/simpla-text#63]
Getting `el.value` returns a HTML string of all inner content (including ProseMirror `<style>` widget). It should only include the _content_ of simpla-text (ie: HTML string returned by `get`).

This broke home title on simpla.io, FWIW, and is a nasty gotcha.

UPDATE: Only occurs on elements with `inline` true. This also means that _every_ simpla-text with inline mode set to true will have corrupted data currently saved on Simpla's API.

**Comment by bedeoverend** [comment]
@seaneking I can't replicate this on master i.e. editing content and getting values out from it. Do you have steps to reproduce with fresh content / master?

What I'm thinking is it might have been an older bug, which meant it was using `innerHTML` even when the `editor` was available, and saved that `style` tag, so is now getting the `style` tag on subsequent loads. If you edit the heading on Simpla.io, as soon as you make any kind of edit, the `el.value` returns the proper purged version - at least for me anyway.

**Comment by seaneking** [comment]
Ah okay so just corrupt day a on simpla.io, sorry should have made a proper repro before filing issue.

**Comment by bedeoverend** [comment]
All good 👍 Worth flagging regardless, should keep an eye out for regression. Pretty sure text's E2E tests should cover it (need to get e2e setup on CI though)

**Comment by bedeoverend** [comment]
I've come across this again on content I recently saved. So definitely still an open bug, reopening and will investigate.

**Comment by seaneking** [comment]
Was your original repro test with `inline` set to true? That was the fail case for me, with simpla-text.

**Comment by bedeoverend** [comment]
Don't think so - though it may have been implicitly set to `inline`, rather than automatically.

**Comment by bedeoverend** [comment]
Got this replicating in both inline and non-inline. Turned out to be a bug where the `value` of the element had been set before the `editor` was loaded in, and once loaded in it re-parsed the content but tried to set it back to the element's `value` before the editor was properly registered. Anyway, patch in #64
