### ISSUE TITLE
Problems with Polymer 2 // Failed to execute 'define' on 'CustomElementRegistry'

### ISSUE THREAD

**Issue by deaththeeny** [SimplaElements/simpla-text#65]
Hello!

I started a web project with the polymer-starter-kit and using Polymer 2 and i really want to use your cms, it's exactly what I need for my project :)

But it doesn't work :( I get this in the console: 
`Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': "undefined" is not a valid custom element name
    at Function.window.Polymer._polymerFn (http://127.0.0.1:8081/bower_components/polymer/lib/legacy/polymer-fn.html:44:22)
    at window.Polymer (http://127.0.0.1:8081/bower_components/polymer/lib/utils/boot.html:29:27)
    at http://127.0.0.1:8081/bower_components/simpla-text/simpla-text.html:1:4466
    at http://127.0.0.1:8081/bower_components/simpla-text/simpla-text.html:1:4477
window.Polymer._polymerFn @ polymer-fn.html:44
window.Polymer @ boot.html:29
(anonymous) @ simpla-text.html:1
(anonymous) @ simpla-text.html:1` 

(same error in simpla-admin, i also setup simpla, include all files etc)

I asked a friend and he told me I could try to use the "polymer.html" file instead of "polymer-element.html" to load the files for polymer 1.

But, nothing other happens 😿 

I hope to hear from you soon and you can help me :)

Greets, Denise

**Comment by madeleineostoja** [comment]
Hey Denise, unfortunately Simpla's elements are still using Polymer 1. Migrating the whole ecosystem to Web Components v1 (ie: Polymer 2+) is a high priority item for us. Follow https://github.com/simplajs/simpla/issues/79 for progress

**Comment by deaththeeny** [comment]
Hey Sean, 
thank you for your response! I thought maybe it could worked with the Polymer 1 compatibility layer. And thank you for this great component. :) I'll follow the progress.
